- name: Install apt packages
  become: true
  apt:
    name:
      - git
      - zsh
      # prerequisites for neovim
      - ninja-build
      - gettext
      - cmake
      - make
      - unzip
      - curl
      - lsb-release
      - ca-certificates
