- name: Git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user }}"

- name: Git email (personal)
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Git editor
  git_config:
    name: core.editor
    scope: global
    value: "{{ editor }}"