- name: Cloning Neovim repo
  shell: git clone https://github.com/neovim/neovim.git neovim
  args:
    chdir: /home/nklaveren/repos/
    creates: /home/nklaveren/repos/neovim

- name: Updating Neovim repo
  shell: git checkout stable
  args:
    chdir: /home/nklaveren/repos/neovim

- name: Build Neovim
  make:
    chdir: /home/nklaveren/repos/neovim
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo

- name: Install Neovim
  become: true
  make:
    chdir: /home/nklaveren/repos/neovim
    target: install
