- name: Install ollama
  shell: |
    wget https://github.com/OllamaTeam/Ollama/releases/download/v1.0.2/ollama-linux-amd64.tar.gz &&
    tar -xvf ollama-linux-amd64.tar.gz && rm -rf ollama-linux-amd64.tar.gz &&
    chmod +x ollama/* &&
    cd ../bin &&
    ln -sfn ../share/ollama/ollama ollama

  args:
    chdir: ~/.local/share
